server:
  port: 8080
spring:
  application:
    name: moviefun
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN

#movies.ms.url: http://localhost:8081/movies
#podcasts.ms.url: http://localhost:8090/podcasts
